version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "2001:2001"
    network_mode: host
    volumes:
      - ~/.homeeup:/root/.homeeup
    environment:
      - LOG=debug
